app/__init__.py
from flask import Flask

from app import settings
from app import views


def create_app():
    app = Flask(__name__)
    app.config.from_object(settings)

    app.register_blueprint(views.blog.bp)
    app.register_blueprint(views.contact.bp)
    app.register_blueprint(views.instructions.bp)
    app.register_blueprint(views.index.bp)

    return app

app/views/__init__.py
from . import blog
from . import contact
from . import instructions
from . import index

app/views/blog.py
from flask import Blueprint, render_template

bp = Blueprint("blog", __name__, url_prefix="/blog")


@bp.route("/")
def index():
    return render_template("blog.html")

app/views/contact.py
from flask import Blueprint, render_template

bp = Blueprint("contact", __name__, url_prefix="/contact")


@bp.route("/")
def index():
    return render_template("contact.html")

app/views/index.py
import os
from datetime import datetime

from flask import (
    Blueprint,
    request,
    flash,
    redirect,
    render_template,
)

from werkzeug.utils import secure_filename

from app import settings
from app import tools

bp = Blueprint('index', __name__, url_prefix='/')

@bp.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        if request.form["sid"] == "" or request.form["token"] == "":
            flash("Twilio ID and token required")
            return redirect(request.url)

        sid = request.form["sid"]
        token = request.form["token"]

        if not tools.valid_credentials(sid, token):
            flash("Invalid Twilio credentials. Please double check your Twilio account SID and token and try again")
            return redirect(request.url)

        if "file" not in request.files:
            flash("No file selected")
            return redirect(request.url)

        file = request.files["file"]
        if file.filename == "":
            flash("No file selected")
            return redirect(request.url)

        if file and tools.allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(
                os.path.join(
                    settings.UPLOAD_FOLDER,
                    filename
                )
            )

            number_list = tools.get_number_list(filename)
            wrong_numbers = tools.check_numbers(number_list, sid, token)

            if wrong_numbers:
                with open(settings.LOG_FILE, "a") as log_file:
                    log_string = f"{datetime.now()} - {len(wrong_numbers)} wrong numbers identified."
                    log_file.write(f"\n{log_string}")
                return render_template(
                    "wrong_numbers.html",
                    number_list=wrong_numbers
                )

            number_list = tools.send_messages(number_list, sid, token)
            return render_template("report.html", number_list=number_list)
        else:
            flash("File type not allowed. Please select a CSV file")
            return redirect(request.url)

    return render_template("index.html")

app/views/instructions.py
from flask import Blueprint, render_template

bp = Blueprint("instructions", __name__, url_prefix="/instructions")


@bp.route("/")
def index():
    return render_template("instructions.html")

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-GG6BQE5E5E"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-GG6BQE5E5E');
        </script>
        <script data-ad-client="ca-pub-8796205311728177" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <title>{% block title %}{% endblock %} - Bulk SMS Sender</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid ">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url_for('index.index') }}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>  Batch SMS Sender</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('index.index') }}">Home <span class="sr-only">(current)</span></a></li>
                        <li><a href="{{ url_for('instructions.index') }}">Instructions</a></li>
                        <li><a href="{{ url_for('blog.index') }}">Blog</a></li>
                        <li><a href="https://github.com/sbestetti/sms-sender">Source</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ url_for('contact.index') }}">Contact</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
            </nav>

        <div class="container">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h3>Error!</h3>
                    </div>
                    <div class="panel-body">
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endif %}
            {% endwith %}
            <div class="jumbotron">
                <h1>Bulk SMS Sender</h1>
                <p>Send bulk SMS messages, without coding. Get started for free!</p>
            </div>
            {% block content %}
            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/blog.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}

{% block content %}
    <h1>Blog entries</h1>>
    Coming soon
{% endblock %}

app/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact information{% endblock %}

{% block content %}
    <h1>Contact information</h1>
    Thank you for your interest and support. If you have any questions or comments please send me an email: <a href="mailto:sergio@bestetti.net">sergio@bestetti.net</a><br>
    Also feel free to connect on <a href="https://www.linkedin.com/in/sergio-bestetti/">LinkedIn</a> and on <a href="https://github.com/sbestetti">GitHub</a>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-alert" aria-hidden="true"></span> First, some important stuff</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>This site is not related to nor supported or endorsed by Twilio Inc. in any way</li>
                <li>This site just provides a simple interface for Twilio's SMS service and it's usage is free of charge</li>
                <li>You'll probably be charged by Twilio though. For the latest info on pricing please check <a href="https://www.twilio.com/sms/pricing/us" target="_blank">this page</a></li>
                <li>This site doesn't store your credentials in any form but it's still safer to use tokens. Please check <a href="https://www.twilio.com/docs/iam/access-tokens#creating-tokens" target="_blank">this page</a> for instructions on how to do it</li>
                <li>The source code for this site is available on <a href="https://github.com/sbestetti/sms-sender" target="_blank">GitHub</a></li>
                <li>Please drop me a message if you need help or if there's anything wrong with this site: <a href="mailto: sbestetti@gmail.com">sbestetti@gmail.com</a></li>
            </ul>
        </div>
    </div>
    <p>
        Welcome to the Batch SMS Sender. The idea of this tool is to enable small companies, entrepreneurs and practices to use SMS messaging to engage it's customer base without having to code anything. Twilio's APIs for messaging are great but they are still APIs and they do require
        some level of knowledge in programming to be used. This tool tries to solve that, allowing you to send bulk messages from a simple spreadsheet. So please head on over to our <a href="{{ url_for('instructions.index') }}">instructions page</a> if this is your first time here and let's get
        started!
        <div id="upload_form" class="form-inline">
            <form method="post" enctype="multipart/form-data">
                    <div class="mt-15">
                        <input type="text" class="form-control" placeholder="Twilio Account SID" aria-describedby="basic-addon1" name="sid" size="50">
                    </div>
                    <div class="mt-15">
                        <input type="password" class="form-control" placeholder="Twilio Token" aria-describedby="basic-addon1" name="token" size="50">
                    </div>
                <div class="mt-15">
                    <input type="file" name="file">
                </div>
                <div class="mt-15">
                    <input type="submit" value="Send messages">
                </div>
            </form>
        </div>
    </p>
{% endblock %}

app/templates/instructions.html
{% extends 'base.html' %}

{% block title %}Instructions{% endblock %}

{% block content %}
    <h1>Instructions</h1>

    <h3>First things first <small>what is Twilio?</small></h3>
    <p>
        Twilio is a platform that offers telecom services in a way that is easy for developers to integrate with applications. These services include SMS, Whatsapp, Voice calls, etc.
        What they <strong>don't</strong> offer is a simple interface for people who doesn't know coding to use their services. And that's where this tool comes in.
        This tools uses your Twilio account to send SMS messages from a simple spreadsheet file. This guide will take you all the way from setting up your Twilio account to delivering your first message. Let's get started!
    </p>

    <div class="mt-50">
        <h3>1 - Getting a Twilio account and credentials<small> go ahead, it's free and doesn't require a credit card</small></h3>
        <p>
            First thing you'll need to do is signup for a Twilio account. Head on over to <a href="https://www.twilio.com/try-twilio" target="_blank">Twilio's signup page</a>, fill the form and hit "Start your free trial". Once you finish setting up your account
            you'll be taken to your dashboard. This is where you'll get your <strong>Account SID</strong> and <strong>Token</strong>, which we'll use to send your messages. Check the following screenshot: the red boxes show you where these fields are on your dashboard.
            Notice that your Token won't be visible. Click on the button shown to display your password. Save both the Account SID and Token, as we'll use them shortly.
        </p>
        <a href="{{ url_for('static', filename='tutorial_001.png') }}">
            <img class="media-object" src="{{ url_for('static', filename='tutorial_001.png') }}" alt="Where to get your credentials" width="80%" height="80%" style="vertical-align:middle;margin:50px 50px">
        </a>
    </div>

    <div class="panel panel-warning">
        <div class="panel-heading">
            <h4>A word about passwords and security</h4>
        </div>
        <div class="panel-body">
            As stated above, this site doesn't store your credentials in any way. But I wouldn't ask you to just take my word for it. That's why I recommend that you use a <strong>Token</strong>
            instead of your Twilio password. This might be a bit advanced for most of the users but if you have some understanding of API security, please follow <a href="https://www.twilio.com/docs/iam/access-tokens" target="_blank">this article</a> to create
            a token. You can just use a token on the "Password" field instead of your Twilio password.
        </div>
    </div>

    <div class="media mt-50">
        <div class="media-body">
            <h3 class="media-heading">2 - Getting a phone number</h3>
            You'll probably need a phone number on your Twilio account in order to send your messages from. I say probably because there are ways of sending messages without a number. Click <a href="https://support.twilio.com/hc/en-us/articles/223181348-Alphanumeric-Sender-ID-for-Twilio-Programmable-SMS" target="_blank">here</a> to
            read more about Alphanumeric Sender IDs. For now, let's stick with a regular number. On your Twilio Dashboard, click on the Hash symbol on the left side of the screen. If it's not visible, expand the menu by clicking on the "three dots" button at the bottom.
        </div>
        <div class="media-right media-middle">
            <img class="media-object" src="{{ url_for('static', filename='tutorial_002.png') }}" alt="Getting a phone number">
        </div>
    </div>
    <p>
        On the "Active Numbers" screen, click on the blue "Buy a number" button on the top right corner. Select the country where you want your new number to be and make sure you check the box for "SMS", under <strong>Capabilites</strong>. This will ensure your new number can send SMS messages.
        If you cannot find a number for your contry you can go with a US number as they have the best delivery rate anywhere in the world. Once this is done click on the red <strong>Search</strong> button. Pick a number for from the list and click on "Buy" on the right side. Review the charges
        and confirm the purchase. Make note of the number as we'll need it when creating the document that will send your messages. That's all we need from Twilio right now. Next we are going to create the list of contacts to which we'll send the messages.
    </p>

    <div class="media mt-50">
        <div class="media-body">
            <h3 class="media-heading">3 - Setting up the list of contacts and message</h3>
            Now we'll use a spreadsheet software (like Excel) to create a list of contacts and messages that we'll use to send the SMS. I've done this example using Google Sheets but any software will do (Excel, Numbers, LibreOffice, etc):
            <ol>
                <li>Open your spreadsheet software and start by entering your Twilio phone number on the first cell (A1).</li>
                <li>On the next column (B1) you enter the destination phone number. Make sure to include country and area code.</li>
                <li>On the third column (C1) you enter the message you want to send.</li>
            </ol>
            That's it! You can copy and paste the message and Twilio phone number to all other rows if they are the same and just fill the B column with your destination phone numbers.
        </div>
        <div class="media-right media-middle">
            <a href="{{ url_for('static', filename='tutorial_003.png') }}">
                <img class="media-object" src="{{ url_for('static', filename='tutorial_003.png') }}" alt="Sample sheet" style="vertical-align:middle;margin:50px 50px">
            </a>
        </div>
    </div>

    <h3>4 - Export the file and upload it to our website</h3>
    <p>
        Now you just need to save your spreadsheet on the format our site can use and upload it to us. How to do that might differ a bit from app to app:
        <ul>
            <li>On <strong>Google Sheets</strong> click on "File", "Download", "Comma-separated values (.csv, current sheet)</li>
            <li>On <strong>Excel</strong> </li> click on "File" and then in "Save as". On the "File Format" box select "Comma Separated Values (.csv)"
            <li>On <strong>Numbers for Mac</strong>click on "File", "Export to", "CSV" and proceed to save the file</li>
            <li>On <strong>OpenOffice</strong></li> click on "File", "Save as" and set "File type" as "Text CSV (.csv)"
        </ul>
        Once you have you file ready go back to our <a href="{{ url_for('index.index') }}">home page</a> and use the form at the bottom to upload your file and Twilio credentials. That's it! If everything is alright we'll start sending your messages and once we are done we'll show you a full report, so please be patient!
    </p>
{% endblock %}

app/templates/report.html
{% extends 'base.html' %}

{% block title %}Report{% endblock %}

{% block content %}
    <div class="alert alert-success">
        <strong>Messages sent!</strong>
        Your messages were succesfully sent. Please check status below
    </div>
    <div class="report">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Destination</th>
                    <th>Status</th>
                    <th>SID</th>
                </tr>
            </thead>
            <tbody>
                {% for item in number_list %}
                    <tr>
                        <td>{{ item[1] }}</td>
                        <td>{{ item[3] }}</td>
                        <td>{{ item[4] }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/templates/wrong_numbers.html
{% extends 'base.html' %}

{% block title %}Wrong numbers{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Incorrect numbers</h1>
    </div>
    <div class="well">
        <p>
            Some of the numbers on your list couldn't be found. Please check them to make sure they are on the correct format, with the Country Code and try again.
        </p>
    </div>
    <div class="report">
        <ul>
            {% for number in number_list %}
                <li>{{ number[1] }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}